//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineQuiz
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_Questions
    {
        public int QuestionId { get; set; }
        [Required(ErrorMessage = "Please provide Question", AllowEmptyStrings = false)]
        public string Question { get; set; }
        [Required(ErrorMessage = "Please provide Correct Answer", AllowEmptyStrings = false)]
        public string CorrectAnswer { get; set; }
        public bool IsMultipleChoice { get; set; }
        public string Option1 { get; set; }
        public string Option2 { get; set; }
        public string Option3 { get; set; }
        public string Option4 { get; set; }
        public bool IsQuizQuestion { get; set; }
    }
}
