//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineQuiz
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_Quiz
    {
        public int QuizId { get; set; }
        [Required(ErrorMessage = "Please provie Quiz Name", AllowEmptyStrings = false)]
        public string QuizName { get; set; }
        public string QuizInstructions { get; set; }
    }
}
